version: "3.9"

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 567234
      POSTGRES_DB: hw02
    volumes:
      - pgdata:/var/lib/postgresql/data

  web:
    build: .
    ports:
      - "8000:80"
    environment:
      SQLALCHEMY_DATABASE_URL: postgresql+psycopg2://postgres:567234@db:5432/hw02
    depends_on:
      - db

volumes:
  pgdata:
